# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('main', '0002_auto_20160714_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='part_speech',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
